force_keyboard_focus = false    # forces keyboard forcus to stay in Walker
close_when_open = true          # close walker when invoking while already opened
click_to_close = true           # closes walker if clicking outside of the main content area
selection_wrap = false          # wrap list if at bottom or top
global_argument_delimiter = "#" # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
exact_search_prefix = "'"       # disable fuzzy searching
theme = "tokyo-night"           # theme to use
additional_theme_location = "~/.local/share/dotfiles/default/walker/themes/"
disable_mouse = false           # disable mouse (on input and list only)
debug = false                   # enables debug printing for some stuff, f.e. keybinds

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Search", list = "No Results" }
"menus:system" = { input = "System", list = "No Results" }
"menus:menu" = { input = "Search", list = "No Results" }
"menus:backups" = { input = "Backups", list = "No Results" }
"menus:capture" = { input = "Capture", list = "No Results" }
"menus:tools" = { input = "Tools", list = "No Results" }
"menus:setup" = { input = "Setup", list = "No Results" }
"menus:themes" = { input = "Themes", list = "No Results" }
"menus:keybindings" = { input = "Keybindings", list = "No Results" }

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
toggle_exact = ["ctrl e"]
resume_last_query = ["ctrl r"]
quick_activate = []

[providers]
default = [
  "desktopapplications"
]
empty = ["desktopapplications"]
previews = [
  "files",
  "clipboard"
]
max_results = 100

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "!"
provider = "todo"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[providers.actions]
dmenu = [
 { action = "select", default = true, bind = "Return" }
]

providerlist = [
  { action = "activate", default = true, bind = "Return", after = "ClearReload" },
]

"menus:screenshots" = [
  { action = "provider:menus:capture", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:system" = [
  { action = "provider:menus:menu", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:setup" = [
  { action = "provider:menus:menu", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:postgres" = [
  { action = "provider:menus:setup", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:capture" = [
  { action = "provider:menus:menu", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:backups" = [
  { action = "provider:menus:tools", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:themes" = [
  { action = "provider:menus:menu", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:tools" = [
  { action = "provider:menus:menu", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:transcode" = [
  { action = "provider:menus:tools", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:ollama" = [
  { action = "provider:menus:tools", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:keybindings" = [
  { action = "provider:menus:menu", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:system-themes" = [
  { action = "provider:menus:themes", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:starship-themes" = [
  { action = "provider:menus:themes", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:fastfetch-themes" = [
  { action = "provider:menus:themes", bind = "Escape", global = true, after = "ClearReload" },
]

"menus:waybar-themes" = [
  { action = "provider:menus:themes", bind = "Escape", global = true, after = "ClearReload" },
]
