pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
// import components.config
import "../theme"

Item {
    id: root

    // Niri Integration
    property int lastNiriRadius: -1

    Process {
        id: niriUpdater
        command: ["sh", "-c", ""]
        onExited: (code) => {
            if (code !== 0) {
                console.warn("Config: Failed to update Niri config (exit code " + code + ")");
            } else {
                console.log("Config: Niri radius updated");
            }
        }
    }

    function updateNiriRadius(r) {
        if (r === lastNiriRadius) return;
        lastNiriRadius = r;
        
        console.log("Config: Updating Niri corner radius to " + r);
        var configFile = Quickshell.env("HOME") + "/.config/niri/style.kdl";
        // Update geometry-corner-radius and reload config
        var cmd = "sed -i -E 's/(geometry-corner-radius\\s+)[0-9]+/\\1" + r + "/' " + configFile + " && niri msg action load-config-file";
        niriUpdater.command = ["sh", "-c", cmd];
        niriUpdater.running = true;
    }

    // Apply config when ConfigLoader finishes
    Connections {
        target: ConfigLoader
        ignoreUnknownSignals: true
        function onConfigReloaded() {
            root._applyConfig();
        }
    }
    
    // Apply dynamic theme colors when generated
    Connections {
        target: DynamicThemeGenerator
        ignoreUnknownSignals: true
        function onColorsGenerated() {
            // Matugen has finished and written dynamic-colors.json
            // ConfigLoader will detect file change and reload themes
            // Then configReloaded signal will trigger _applyConfig
            // which will now have the updated dynamic theme colors
            console.log("DynamicTheme: Colors generated, ConfigLoader will reload");
        }
    }

    // Reload function
    function reload() {
        ConfigLoader.reload();
    }

    // Helper to resolve ~ paths
    function resolvePath(path) {
        if (!path) return "";
        if (path.startsWith("~")) {
            return Quickshell.env("HOME") + path.substring(1);
        }
        return path;
    }

    // Base configuration directory
    property string configDir: Quickshell.env("HOME") + "/.config/quickshell"

    // Apply merged config and themes
    function _applyConfig() {
        var cfg = ConfigLoader.config || {};
        console.log("DEBUG: Config loaded. Animations section: " + JSON.stringify(cfg.animations));
        var themes = ConfigLoader.themes || {};

        // Check if dynamic theme is selected
        root.dynamicThemeEnabled = (cfg.theme === "dynamic" || cfg.theme === "dynamic-inverted");

        // Apply wallpaper first (needed for dynamic theme)
        if (cfg.wallpaper) {
            root.wallpaperPath = root.resolvePath(cfg.wallpaper);
        }

        // Apply theme (works for both static and dynamic themes now)
        // Prioritize shellTheme for colors, but use theme for system-wide sync
        if (cfg.theme) {
            root.currentTheme = cfg.theme;
        }
        
        // Use shellColors if available (from ShellThemeProvider), otherwise use theme
        if (cfg.shellColors) {
            // Direct color override from ShellThemeProvider (bypasses tinty/matugen)
            console.log("Config: Using shellColors from config");
            if (cfg.shellColors.background) root.background = cfg.shellColors.background;
            if (cfg.shellColors.foreground) root.foreground = cfg.shellColors.foreground;
            if (cfg.shellColors.accent) root.accent = cfg.shellColors.accent;
            if (cfg.shellColors.red) root.red = cfg.shellColors.red;
            if (cfg.shellColors.green) root.green = cfg.shellColors.green;
            if (cfg.shellColors.yellow) root.yellow = cfg.shellColors.yellow;
            if (cfg.shellColors.orange) root.orange = cfg.shellColors.orange;
            if (cfg.shellColors.cyan) root.cyan = cfg.shellColors.cyan;
            if (cfg.shellColors.blue) root.blue = cfg.shellColors.blue;
            if (cfg.shellColors.purple) root.purple = cfg.shellColors.purple;
            if (cfg.shellColors.magenta) root.magenta = cfg.shellColors.magenta;
            if (cfg.shellColors.statusCritical) root.statusCritical = cfg.shellColors.statusCritical;
            if (cfg.shellColors.statusWarning) root.statusWarning = cfg.shellColors.statusWarning;
            if (cfg.shellColors.statusMedium) root.statusMedium = cfg.shellColors.statusMedium;
            if (cfg.shellColors.statusGood) root.statusGood = cfg.shellColors.statusGood;
        } else {
            // Use shellTheme if set, otherwise fallback to theme
            var activeTheme = cfg.shellTheme || cfg.theme;
            
            if (activeTheme) {
                var layoutTheme = themes[activeTheme];
                var colorTheme = themes[activeTheme];

                // For base16 themes, use "current" theme colors (generated by tinty hook)
                // BUT keep using the specific theme for layout if available
                if (activeTheme.startsWith("base16-") && themes["current"]) {
                    colorTheme = themes["current"];
                    // If the specific theme doesn't exist in themes.json (no layout override), fallback to current
                    if (!layoutTheme) {
                        layoutTheme = themes["current"];
                    }
                } else if (!layoutTheme) {
                    // Fallback if theme not found at all
                    layoutTheme = themes["current"];
                }
                
                // Apply theme colors
                if (colorTheme && colorTheme.colors) {
                    var c = colorTheme.colors;
                    if (c.background) root.background = c.background;
                    if (c.foreground) root.foreground = c.foreground;
                    if (c.accent) root.accent = c.accent;
                    if (c.red) root.red = c.red;
                    if (c.green) root.green = c.green;
                    if (c.yellow) root.yellow = c.yellow;
                    if (c.orange) root.orange = c.orange;
                    if (c.cyan) root.cyan = c.cyan;
                    if (c.blue) root.blue = c.blue;
                    if (c.purple) root.purple = c.purple;
                    if (c.magenta) root.magenta = c.magenta;
                    if (c.statusCritical) root.statusCritical = c.statusCritical;
                    if (c.statusWarning) root.statusWarning = c.statusWarning;
                    if (c.statusMedium) root.statusMedium = c.statusMedium;
                    if (c.statusGood) root.statusGood = c.statusGood;
                }

                // Apply theme layout
                if (layoutTheme && layoutTheme.layout) {
                    var l = layoutTheme.layout;
                    if (l.radius !== undefined) root.radius = l.radius;
                    if (l.itemRadius !== undefined) root.itemRadius = l.itemRadius;
                    if (l.screenCornerRadius !== undefined) {
                         root.screenCornerRadius = l.screenCornerRadius;
                         // Update Niri immediately with the target value (ignoring animation)
                         if (l.screenCornerRadius !== root.lastNiriRadius) {
                             root.updateNiriRadius(l.screenCornerRadius);
                         }
                    }
                    if (l.panelCornerRadius !== undefined) root.panelCornerRadius = l.panelCornerRadius;
                    if (l.screenBorderSize !== undefined) root.screenBorderSize = l.screenBorderSize;
                }
            }
        }

        // For dynamic theme: update DynamicThemeGenerator state
        // ThemeSync will handle running matugen when wallpaper/theme changes
        if (root.dynamicThemeEnabled) {
            DynamicThemeGenerator.wallpaperPath = root.wallpaperPath;
            DynamicThemeGenerator.inverted = (cfg.theme === "dynamic-inverted");
        }

        // Override with explicit config values (colors override theme)
        if (cfg.colors) {
            if (cfg.colors.background) root.background = cfg.colors.background;
            if (cfg.colors.foreground) root.foreground = cfg.colors.foreground;
            if (cfg.colors.accent) root.accent = cfg.colors.accent;
            if (cfg.colors.red) root.red = cfg.colors.red;
            if (cfg.colors.green) root.green = cfg.colors.green;
            if (cfg.colors.yellow) root.yellow = cfg.colors.yellow;
            if (cfg.colors.orange) root.orange = cfg.colors.orange;
            if (cfg.colors.cyan) root.cyan = cfg.colors.cyan;
            if (cfg.colors.blue) root.blue = cfg.colors.blue;
            if (cfg.colors.purple) root.purple = cfg.colors.purple;
            if (cfg.colors.magenta) root.magenta = cfg.colors.magenta;
            if (cfg.colors.statusCritical) root.statusCritical = cfg.colors.statusCritical;
            if (cfg.colors.statusWarning) root.statusWarning = cfg.colors.statusWarning;
            if (cfg.colors.statusMedium) root.statusMedium = cfg.colors.statusMedium;
            if (cfg.colors.statusGood) root.statusGood = cfg.colors.statusGood;
        }

        // Layout overrides (always apply, even with dynamic theme)
        if (cfg.layout) {
            if (cfg.layout.radius !== undefined) root.radius = cfg.layout.radius;
            if (cfg.layout.itemRadius !== undefined) root.itemRadius = cfg.layout.itemRadius;
            if (cfg.layout.screenCornerRadius !== undefined) root.screenCornerRadius = cfg.layout.screenCornerRadius;
            if (cfg.layout.panelCornerRadius !== undefined) root.panelCornerRadius = cfg.layout.panelCornerRadius;
            if (cfg.layout.screenBorderSize !== undefined) root.screenBorderSize = cfg.layout.screenBorderSize;
            if (cfg.layout.panelEdgeRevealDelay !== undefined) root.panelEdgeRevealDelay = cfg.layout.panelEdgeRevealDelay;
            if (cfg.layout.padding !== undefined) root.padding = cfg.layout.padding;
            if (cfg.layout.spacing !== undefined) root.spacing = cfg.layout.spacing;
            if (cfg.layout.buttonSize !== undefined) root.buttonSize = cfg.layout.buttonSize;
            if (cfg.layout.iconSize !== undefined) root.iconSize = cfg.layout.iconSize;
            if (cfg.layout.panelWidth !== undefined) root.panelWidth = cfg.layout.panelWidth;
        }

        // Panels
        if (cfg.panels) {
            if (cfg.panels.screen !== undefined) root.panelsScreen = cfg.panels.screen;
        }

    // Animation overrides
        if (cfg.animations) {
            // New Structured Config Support
            if (cfg.animations.global) {
                if (cfg.animations.global.fast !== undefined) root.animDurationFast = cfg.animations.global.fast;
                if (cfg.animations.global.regular !== undefined) root.animDurationRegular = cfg.animations.global.regular;
                if (cfg.animations.global.slow !== undefined) root.animationDurationSlow = cfg.animations.global.slow;
                if (cfg.animations.global.easing) root.animEasingStandard = root._resolveEasing(cfg.animations.global.easing);
                
                // Backwards compat aliases
                root.animationDurationQuick = root.animDurationFast;
                root.animationDurationMedium = root.animDurationRegular;
                root.animationDuration = root.animDurationRegular;
            }
            
            if (cfg.animations.panel) {
                if (cfg.animations.panel.reveal !== undefined) root.animationDurationLong = cfg.animations.panel.reveal;
                if (cfg.animations.panel.autoHideDelay !== undefined) root.autoHideDelay = cfg.animations.panel.autoHideDelay;
                
                // Reset to default before checking
                root.animCurvePanel = null;
                
                if (cfg.animations.panel.easing) {
                    root.animEasingPanel = root._resolveEasing(cfg.animations.panel.easing);
                    // Special case for Polar Bezier
                    if (cfg.animations.panel.easing === "Polar") {
                        console.log("Config: Enabling Polar Bezier for Panels");
                        root.animCurvePanel = root.animCurvePolar;
                    }
                }
            }
            
            if (cfg.animations.feedback) {
                if (cfg.animations.feedback.hover !== undefined) root.animDurationHover = cfg.animations.feedback.hover;
                if (cfg.animations.feedback.shake !== undefined) root.animDurationShake = cfg.animations.feedback.shake;
                if (cfg.animations.feedback.pulse !== undefined) root.animDurationPulse = cfg.animations.feedback.pulse;
                if (cfg.animations.feedback.easingPulse) root.animEasingPulse = root._resolveEasing(cfg.animations.feedback.easingPulse);
                if (cfg.animations.feedback.easingBounce) root.animEasingBounce = root._resolveEasing(cfg.animations.feedback.easingBounce);
            }
            
            if (cfg.animations.screensaver) {
                if (cfg.animations.screensaver.step !== undefined) root.animDurationSaverStep = cfg.animations.screensaver.step;
                if (cfg.animations.screensaver.fast !== undefined) root.animDurationSaverFast = cfg.animations.screensaver.fast;
                if (cfg.animations.screensaver.medium !== undefined) root.animDurationSaverMedium = cfg.animations.screensaver.medium;
                if (cfg.animations.screensaver.slow !== undefined) root.animDurationSaverSlow = cfg.animations.screensaver.slow;
                if (cfg.animations.screensaver.verySlow !== undefined) root.animDurationSaverVerySlow = cfg.animations.screensaver.verySlow;
            }
            
            if (cfg.animations.misc) {
                if (cfg.animations.misc.background !== undefined) root.animDurationBackground = cfg.animations.misc.background;
                if (cfg.animations.misc.pause !== undefined) root.animDurationPause = cfg.animations.misc.pause;
            }

            // Fallback for flat structure (legacy support)
            if (cfg.animations.durationQuick !== undefined) root.animationDurationQuick = cfg.animations.durationQuick;
            if (cfg.animations.durationMedium !== undefined) root.animationDurationMedium = cfg.animations.durationMedium;
            if (cfg.animations.durationSlow !== undefined) root.animationDurationSlow = cfg.animations.durationSlow;
            if (cfg.animations.autoHideDelay !== undefined) root.autoHideDelay = cfg.animations.autoHideDelay;
            
            if (cfg.animations.durationFast !== undefined) root.animDurationFast = cfg.animations.durationFast;
            if (cfg.animations.durationRegular !== undefined) root.animDurationRegular = cfg.animations.durationRegular;
            if (cfg.animations.durationHover !== undefined) root.animDurationHover = cfg.animations.durationHover;
            if (cfg.animations.durationShake !== undefined) root.animDurationShake = cfg.animations.durationShake;
            if (cfg.animations.durationPulse !== undefined) root.animDurationPulse = cfg.animations.durationPulse;
            if (cfg.animations.durationBackground !== undefined) root.animDurationBackground = cfg.animations.durationBackground;
            if (cfg.animations.durationPause !== undefined) root.animDurationPause = cfg.animations.durationPause;
            
            if (cfg.animations.saverStep !== undefined) root.animDurationSaverStep = cfg.animations.saverStep;
            if (cfg.animations.saverFast !== undefined) root.animDurationSaverFast = cfg.animations.saverFast;
            if (cfg.animations.saverMedium !== undefined) root.animDurationSaverMedium = cfg.animations.saverMedium;
            if (cfg.animations.saverSlow !== undefined) root.animDurationSaverSlow = cfg.animations.saverSlow;
            if (cfg.animations.saverVerySlow !== undefined) root.animDurationSaverVerySlow = cfg.animations.saverVerySlow;
        }

        // Fonts
        if (cfg.fonts) {
            if (cfg.fonts.family) root.fontFamily = cfg.fonts.family;
            if (cfg.fonts.iconFamily) root.iconFontFamily = cfg.fonts.iconFamily;
        }

        // Icon Theme
        if (cfg.iconTheme) root.iconTheme = cfg.iconTheme;

        // Pomodoro
        if (cfg.pomodoro) {
            if (cfg.pomodoro.duration !== undefined) root.pomodoroDuration = cfg.pomodoro.duration;
            if (cfg.pomodoro.breakDuration !== undefined) root.pomodoroBreakDuration = cfg.pomodoro.breakDuration;
            if (cfg.pomodoro.longBreakDuration !== undefined) root.pomodoroLongBreakDuration = cfg.pomodoro.longBreakDuration;
            if (cfg.pomodoro.cycleCount !== undefined) root.pomodoroCycleCount = cfg.pomodoro.cycleCount;
        }

        // Clock
        if (cfg.clock) {
            if (cfg.clock.dateFormat !== undefined) root.clockDateFormat = cfg.clock.dateFormat;
        }

        // Voice Dictation
        if (cfg.voiceDictation) {
            root.voiceDictation = cfg.voiceDictation;
        }

        // Screensavers list
        if (cfg.screensavers && Array.isArray(cfg.screensavers)) {
             root.activeScreensavers = cfg.screensavers;
        }

        // Chat persistence
        if (cfg.chat) {
            if (cfg.chat.lastAgent !== undefined) root.lastChatAgent = cfg.chat.lastAgent;
            if (cfg.chat.lastProvider !== undefined) root.lastChatProvider = cfg.chat.lastProvider;
            if (cfg.chat.lastModel !== undefined) root.lastChatModel = cfg.chat.lastModel;
        }

        // Shadow
        if (cfg.shadow !== undefined) root.shadow = cfg.shadow;

        console.log("Config applied: theme=" + root.currentTheme);
    }

    function _resolveEasing(name) {
        switch(name) {
            case "Linear": return Easing.Linear;
            case "InQuad": return Easing.InQuad; case "OutQuad": return Easing.OutQuad; case "InOutQuad": return Easing.InOutQuad;
            case "InCubic": return Easing.InCubic; case "OutCubic": return Easing.OutCubic; case "InOutCubic": return Easing.InOutCubic;
            case "InQuart": return Easing.InQuart; case "OutQuart": return Easing.OutQuart; case "InOutQuart": return Easing.InOutQuart;
            case "InQuint": return Easing.InQuint; case "OutQuint": return Easing.OutQuint; case "InOutQuint": return Easing.InOutQuint;
            case "InSine": return Easing.InSine; case "OutSine": return Easing.OutSine; case "InOutSine": return Easing.InOutSine;
            case "InExpo": return Easing.InExpo; case "OutExpo": return Easing.OutExpo; case "InOutExpo": return Easing.InOutExpo;
            case "InCirc": return Easing.InCirc; case "OutCirc": return Easing.OutCirc; case "InOutCirc": return Easing.InOutCirc;
            case "InBack": return Easing.InBack; case "OutBack": return Easing.OutBack; case "InOutBack": return Easing.InOutBack;
            case "InBounce": return Easing.InBounce; case "OutBounce": return Easing.OutBounce; case "InOutBounce": return Easing.InOutBounce;
            case "Polar": return Easing.Bezier; 
            default: return Easing.OutCubic;
        }
    }

    // Wallpaper path (resolved to absolute)
    property string wallpaperPath: Quickshell.env("HOME") + "/.config/quickshell/assets/wallpaper.png"

    // Current theme name
    property string currentTheme: "tokyo-night"

    // Dynamic theme enabled state
    property bool dynamicThemeEnabled: false

    // Colors (defaults from Tokyo Night)
    property color background: "#1a1b26"
    Behavior on background { ColorAnimation { duration: root.animationDuration } }

    property color foreground: "#c0caf5"
    Behavior on foreground { ColorAnimation { duration: root.animationDuration } }

    // Color for text or inactive elements (50% opacity)
    property color dimmed: Qt.alpha(foreground, 0.5)

    property color accent: "#7aa2f7"
    Behavior on accent { ColorAnimation { duration: root.animationDuration } }

    property color red: "#f7768e"
    Behavior on red { ColorAnimation { duration: root.animationDuration } }

    property color green: "#9ece6a"
    Behavior on green { ColorAnimation { duration: root.animationDuration } }

    property color yellow: "#e0af68"
    Behavior on yellow { ColorAnimation { duration: root.animationDuration } }

    property color orange: "#ff9e64"
    Behavior on orange { ColorAnimation { duration: root.animationDuration } }

    property color cyan: "#7dcfff"
    Behavior on cyan { ColorAnimation { duration: root.animationDuration } }

    property color blue: "#7aa2f7"
    Behavior on blue { ColorAnimation { duration: root.animationDuration } }

    property color purple: "#bb9af7"
    Behavior on purple { ColorAnimation { duration: root.animationDuration } }

    property color magenta: "#bb9af7"
    Behavior on magenta { ColorAnimation { duration: root.animationDuration } }

    // Status colors
    property color statusCritical: "#f7768e"
    Behavior on statusCritical { ColorAnimation { duration: root.animationDuration } }

    property color statusWarning: "#ff9e64"
    Behavior on statusWarning { ColorAnimation { duration: root.animationDuration } }

    property color statusMedium: "#e0af68"
    Behavior on statusMedium { ColorAnimation { duration: root.animationDuration } }

    property color statusGood: "#9ece6a"
    Behavior on statusGood { ColorAnimation { duration: root.animationDuration } }

    // Detect if theme is light based on background luminance
    // Luminance formula: 0.299*R + 0.587*G + 0.114*B
    property bool isLightTheme: {
        var r = background.r;
        var g = background.g;
        var b = background.b;
        var luminance = 0.299 * r + 0.587 * g + 0.114 * b;
        return luminance > 0.5;
    }

    // Icon color: dark for light themes, foreground for dark themes
    property color iconColor: isLightTheme ? Qt.darker(foreground, 1.5) : foreground

    // Radius for main window (large)
    property int radius: 10
    Behavior on radius { NumberAnimation { duration: root.animationDuration } }

    // Radius for internal elements (small, e.g. volume bar, workspaces)
    property int itemRadius: 4
    Behavior on itemRadius { NumberAnimation { duration: root.animationDuration } }

    // Corner radius for screen borders
    property int screenCornerRadius: 12
    Behavior on screenCornerRadius { NumberAnimation { duration: root.animationDuration } }

    // Corner radius for panel inverted corners
    property int panelCornerRadius: radius
    Behavior on panelCornerRadius { NumberAnimation { duration: root.animationDuration } }

    // Screen border size (thickness of edge decorations)
    property int screenBorderSize: 4

    // Panel edge reveal delay (ms to hover before panel appears)
    property int panelEdgeRevealDelay: 1000

    // Standard Layout Properties
    property int padding: 10
    property int spacing: 10
    property int buttonSize: 40
    property int iconSize: 18
    property int panelWidth: 320

    // Panel placement mode: "active" | "all" | "<screen-name>"
    property string panelsScreen: "active"

    // Animation Properties (3 speeds: quick, medium, slow)
    property int animationDurationQuick: 150
    property int animationDurationMedium: 300
    property int animationDurationSlow: 500
    
    // New Standardized Durations
    property int animDurationFast: 100        // Borders, hover colors
    property int animDurationRegular: 200     // Generic UI transitions
    property int animDurationHover: 250       // Launcher hover
    property int animDurationShake: 50        // Error shake
    property int animDurationPulse: 800       // Pulse effects
    property int animDurationBackground: 600  // Wallpaper transitions
    
    // Screensaver & Misc
    property int animDurationPause: 400       // Chat typing pause
    property int animDurationSaverStep: 1000
    property int animDurationSaverFast: 2000
    property int animDurationSaverMedium: 4000
    property int animDurationSaverSlow: 5000
    property int animDurationSaverVerySlow: 10000
    
    // Easing Types
    property int animEasingStandard: Easing.OutCubic  // Standard UI movement
    property int animEasingSoft: Easing.OutQuad       // Softer transitions
    property int animEasingPanel: Easing.OutExpo      // Panel reveal
    property var animCurvePanel: null                 // Custom bezier support for panels
    
    // Global Polar Curve Support
    property var polarCurve: [0.38, 1.21, 0.22, 1.0, 1, 1]
    property int animEasingPolar: Easing.Bezier       // Maps to Bezier
    
    property int animEasingPulse: Easing.InOutSine    // Pulse/Breathing
    property int animEasingBounce: Easing.OutBack     // Bouncy entrances

    // Legacy alias for backwards compatibility
    property int animationDuration: animationDurationQuick
    property int animationDurationLong: animationDurationSlow
    property int autoHideDelay: 5000

    // Font configuration
    property string fontFamily: "Cascadia Code"
    property string iconFontFamily: "Symbols Nerd Font, FontAwesome, Cascadia Code"
    
    // Icon Theme
    property string iconTheme: ""

    // Pomodoro
    property int pomodoroDuration: 52
    property int pomodoroBreakDuration: 17
    property int pomodoroLongBreakDuration: 30
    property int pomodoroCycleCount: 4

    // Clock
    property string clockDateFormat: "dd MMM"

    // Voice Dictation
    property var voiceDictation: ({
        "model": "base.en",
        "language": "es"
    })

    // Chat persistence
    property string lastChatAgent: ""
    property string lastChatProvider: ""
    property string lastChatModel: ""

    // Do Not Disturb
    property bool doNotDisturb: false
    
    // Shadow color (defaults to 50% transparent black)
    property color shadow: "#80000000"

    // Active Screensavers List
    property var activeScreensavers: [
        "NiriSaver.qml",
        "PolarSaver.qml",
        "FedoraSaver.qml",
        "QuickshellSaver.qml",
        "ArchSaver.qml",
        "UbuntuSaver.qml",
        "HyprlandSaver.qml",
        "DebianSaver.qml",
        "WaylandSaver.qml",
        "CachySaver.qml"
    ]


    // Setup Connections after singletons are initialized
    Component.onCompleted: {
        // Find the Connections objects and set their targets
        var children = root.children;
        for (var i = 0; i < children.length; i++) {
            var child = children[i];
            if (child.target === null) {
                // First Connections is for ConfigLoader
                if (i === 0) {
                    child.target = ConfigLoader;
                }
                // Second Connections is for DynamicThemeGenerator
                else if (i === 1) {
                    child.target = DynamicThemeGenerator;
                }
            }
        }
    }
}
