[ids]
0001:0001

[main]
capslock = esc

a = overload(control, a)
s = overload(alt, s)
d = overload(shift, d)
f = overload(meta, f)

j = overload(meta, j)
k = overload(shift, k)
l = overload(alt, l)
semicolon = overload(control, semicolon)

