return {}
-- return {
--   'zbirenbaum/copilot.lua',
--   dependencies = {
--     'zbirenbaum/copilot-cmp',
--   },
--   cmd = 'Copilot',
--   build = ':Copilot auth',
--   event = 'InsertEnter',
--   opts = {
--     suggestion = {
--       enabled = true,
--       auto_trigger = true,
--       hide_during_completion = vim.g.ai_cmp,
--       keymap = {
--         accept = '<M-l>',
--         next = '<M-]>',
--         prev = '<M-[>',
--         dismiss = '<C-]>',
--       },
--     },
--     panel = {
--       enabled = true,
--     },
--     filetypes = {
--       markdown = true,
--       help = true,
--       yaml = true,
--     },
--   },
-- }
